stages:
    - build
    - test
    
build:
    stage: build
    script:
        - echo "Begin to build program"
        - touch "DLL Downloader.py"
    
    artifacts:
        paths:
            - ./

test:
    stage: test
    script:
        - echo "began to test"
        - test -f " DLL Downloader.py"